### ISSUE TITLE
Timeformat for period

### ISSUE THREAD

**Issue by jme0** [doksu/thirdman#5]
Hi Douglas
Great little app, I will be happy to test it soon with real life data. Meanwhile I had a quick look into your search. Seems to me that there's a bit of confusion about time format (24h vs am/pm) at 
eval period=case(date_hour<5, 0, date_hour<8, 1, date_hour<12, 2, date_hour<5, 3, date_hour<8, 4, date_hour<24, 5) 
Shouldn't it be instead
eval period=case(date_hour<5, 0, date_hour<8, 1, date_hour<12, 2, date_hour<17, 3, date_hour<20, 4, date_hour<24, 5)

**Comment by doksu** [comment]
You're right, thanks very much for letting me know. BTW, late last year I started working on version 2 of the third man app, which uses tstats/pivot instead of the datamodel command (to be honest, when I wrote version 1 I didn't realise the datamodel command doesn't use acceleration). Version 2 is in the branch 'v2'. I haven't released version 2 yet because so far this year I've been focusing on developing the Linux Auditd app.

Tonight (my time ~ in about 11hrs) there's a few changes I'll make to the 'v2' branch:
1. Fix the bug you're found
2. I found out the other day that the dnsLookup command we had to manually put into transforms (back in Splunk version 4) is no longer required since Splunk 6, so I need to update that in the searches to use the built-in lookup
3. Move the correlation search into its own 'SA-ThirdMan' app. One of the ES developers from Splunk told me that to make the correlation search "appear" in the ES app, rather than adding the thirdman into the ES app's metadata import command, I should rename my app to start with 'SA-' and then it just works.
4. The README needs updating to reflect version 2 changes better (not sure if I'll have time to get to this)

Later on I'd also like to change the correlation search to use ES' provided ASN lookup and update the provided ASN lookup. Once that's sorted I'll probably release version 2. :)

**Comment by doksu** [comment]
Thanks again for your feedback, I've just implemented all those changes and released version 2 of the app on Splunkbase. Be sure to let me know if you find any other issues or have other suggestions ~ it's feedback like yours that helps improve community built apps for everyone. :)

**Comment by jme0** [comment]
Was a pleasure to help. And wow...I triggered a new release :-)
